### ISSUE TITLE
Allow Administrators to Invalidate Finished Boxes

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#53] opened 2012-03-05 04:44 UTC
Sometimes when first teaching people about the tasking server boxes get validated that shouldn't have been.  It would be good to have a way for administrators to invalidate the validation.

**Comment by kiki-denver** [comment] 2014-04-06 23:39
I'm going through feature requests for a data mining project, and noticed that a similar feature request (#55) was marked as Closed. This makes me think that maybe this one should be as well? I am not super familiar with the TM/admin features of the TM at the moment so I am hesitant to mark that change myself; however, I thought I'd bring it to the community's attention.

**Comment by pgiraud** [comment] 2014-04-07 07:36
Well #55 was closed because it was a duplicate of the current one. Not because the issue was fixed.
However this one can be marked as fixed since the validated tasks can now be invalidated at any time by any user.
Closing.
Thanks for your report.

**Closed as completed by pgiraud** 2014-04-07 07:36 UTC
Labels: feature request
